version: '3.8'

services:
  project-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: project-zookeeper
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  project-kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: project-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://project-kafka:9092,INTERNAL://project-kafka:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://project-kafka:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: project-zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
    depends_on:
      - project-zookeeper
  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - project-kafka